pipeline{
    agent any

    stages{
        stage('SCM Checkout'){
            steps{
                git branch: 'feature/jenkinspipeline-stages', credentialsId: '750f9158-6e56-4635-88e3-0dc2c5019156', url: 'https://github.com/Micah-Shallom/ansible-config-mgt.git'
            }
        }
}
}